-- MySQL Script generated by MySQL Workbench
-- Sun Sep 15 21:06:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema suap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema suap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `suap` DEFAULT CHARACTER SET utf8 ;
USE `suap` ;

-- -----------------------------------------------------
-- Table `suap`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suap`.`usuarios` (
  `usuario_id` INT(11) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `nombre_de_usuario` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `suap`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suap`.`administradores` (
  `admin_id` INT(11) NOT NULL,
  PRIMARY KEY (`admin_id`),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`admin_id`)
    REFERENCES `suap`.`usuarios` (`usuario_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `suap`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suap`.`profesores` (
  `id_profesor` INT(11) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `rfc` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_profesor`),
  CONSTRAINT `fk_usuarios`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `suap`.`usuarios` (`usuario_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `suap`.`unidades_de_aprendizaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suap`.`unidades_de_aprendizaje` (
  `unidad_de_aprendizaje_id` INT(11) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `horas_clase` INT(11) NOT NULL,
  `horas_taller` INT(11) NOT NULL,
  `horas_laboratorio` INT(11) NOT NULL,
  PRIMARY KEY (`unidad_de_aprendizaje_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `suap`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suap`.`asignacion` (
  `profesor_id` INT(11) NOT NULL,
  `unidad_de_aprendizaje_id` INT(11) NOT NULL,
  PRIMARY KEY (`profesor_id`, `unidad_de_aprendizaje_id`),
  INDEX `unidad_de_aprendizaje_id` (`unidad_de_aprendizaje_id` ASC) VISIBLE,
  CONSTRAINT `asignacion_ibfk_1`
    FOREIGN KEY (`profesor_id`)
    REFERENCES `suap`.`profesores` (`id_profesor`),
  CONSTRAINT `asignacion_ibfk_2`
    FOREIGN KEY (`unidad_de_aprendizaje_id`)
    REFERENCES `suap`.`unidades_de_aprendizaje` (`unidad_de_aprendizaje_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `suap`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `suap`.`horario` (
  `id_horario` INT(11) NOT NULL,
  `id_unidad_aprendizaje` INT(11) NOT NULL,
  `dia` ENUM('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado') NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `tipo` ENUM('clase', 'taller', 'laboratorio') NOT NULL,
  PRIMARY KEY (`id_horario`),
  INDEX `fk_unidad_aprendizaje` (`id_unidad_aprendizaje` ASC) VISIBLE,
  CONSTRAINT `fk_unidad_aprendizaje`
    FOREIGN KEY (`id_unidad_aprendizaje`)
    REFERENCES `suap`.`unidades_de_aprendizaje` (`unidad_de_aprendizaje_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
